name: Admin Build Test
on:
  push:
  pull_request:
    branches: 
      - '**'
      - '!main'
    paths: 
      - 'admin/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: 'Check admin build'
        working-directory: ./admin
        run: |
          npm ci
          npm run build --if-present


