name: Web Build Test
on:
  pull_request:
    # branches: 
    #   - '**'
    #   - '!main'
    paths: 
      - 'web/**'
  
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./web

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Check Build
        run: npm run build --if-present



