name: Admin Build Test
on:
  pull_request:
    # branches: 
    #   - '**'
    #   - '!main'
    paths: 
      - 'admin/**'
  
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./admin

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: admin-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            admin-
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts
      - name: Check Build
        run: npm run build --if-present


