name: Server Build Test
on:
  pull_request:
    # branches: 
    #   - '**'
    #   - '!main'
    paths: 
      - 'server/**'
  
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./server

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: 'Check server uild'
        run: |
          npm ci
          npm run build --if-present


